version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: prueba_java_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=pedidos_db
      - POSTGRES_USER=user_dev
      - POSTGRES_PASSWORD=password_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: